# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8cae160288ceac7d5d911b721b61d40392141b9dc16ff4aca03f8829fad991822156ac56d48d1609a89c47c297566bd83d0612ae7a9cbb89a54c52c95c4d2757

test:
  secret_key_base: cecf4bae5740bf81009adcb954bfaabfed64ebdece7568d1db7cb7282239ffc8232382ba74a13a41ede905d3dfeacf33da28f039f0c2420511d58f6e0bf4a884

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
